modLoader="javafml"
loaderVersion="[39,)"
license="LGPL-3.0-only"
[[mods]]
modId="oculus"
version="${version}"
displayName="Oculus"
logoFile="oculus-logo.png"
authors="coderbot, IMS212, Justsnoopy30, FoundationGames"
description='''
Unofficial Fork of "Iris", made to work with FML
'''
[mods."sodium:options"]
"mixin.features.entity.fast_render"=false
"mixin.features.gui.font"=false
