modLoader="javafml"
loaderVersion="[39,)"
license="LGPL-3.0-only"
[[mods]]
modId="oculus"
version="1.2.4"
displayName="Oculus"
logoFile="oculus-logo.png"
authors="coderbot, IMS212, Justsnoopy30, FoundationGames"
description='''
Unofficial Fork of "Iris", made to work with FML
'''