contact_links:
  - name: Join the Discord for support using Oculus!
    url: https://discord.com/invite/UCsyn5RS4s
    about: It's easier for our support staff to help you through our Discord server, so please if you are looking for support, go there. Of course, if you have found an actual bug/crash, please open an issue.
